/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PresenceRouteImport } from './routes/presence'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersSlackIdRouteImport } from './routes/users_.$slackId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenceRoute = PresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersSlackIdRoute = UsersSlackIdRouteImport.update({
  id: '/users_/$slackId',
  path: '/users/$slackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/presence': typeof PresenceRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/users/$slackId': typeof UsersSlackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/presence': typeof PresenceRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/users/$slackId': typeof UsersSlackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/docs': typeof DocsRoute
  '/presence': typeof PresenceRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/users_/$slackId': typeof UsersSlackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/docs'
    | '/presence'
    | '/reports'
    | '/users'
    | '/users/$slackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/docs'
    | '/presence'
    | '/reports'
    | '/users'
    | '/users/$slackId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/docs'
    | '/presence'
    | '/reports'
    | '/users'
    | '/users_/$slackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DocsRoute: typeof DocsRoute
  PresenceRoute: typeof PresenceRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  UsersSlackIdRoute: typeof UsersSlackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presence': {
      id: '/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof PresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$slackId': {
      id: '/users_/$slackId'
      path: '/users/$slackId'
      fullPath: '/users/$slackId'
      preLoaderRoute: typeof UsersSlackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DocsRoute: DocsRoute,
  PresenceRoute: PresenceRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  UsersSlackIdRoute: UsersSlackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
